mindmap
  root((Apprenant))
    Voit
      Étudiants stressés
      Environnement formel
      Interface sérieuse
    Entend
      Conseils des formateurs
      Retours des camarades
      Pression familiale
    Dit
      "Je suis stressé pour l’entretien"
      "J’espère bien m’exprimer"
    Fait
      Prépare ses réponses
      Consulte ses mails
      Pose des questions
