mindmap
  root((Apprenant))
    Entend
      Tu dois être autonome dans ton apprentissage
      Les vidéos et ressources sont parfois trop longues ou complexes
      J'ai besoin d'aide, mais je ne sais pas toujours à qui m'adresser
    Dit
      Je n'ai pas compris ce concept, j'ai besoin d'aide
      Je vais essayer de comprendre par moi-même
      C'est difficile de rester concentré avec ce format
    Fait
      Remplir des formulaires de feedback
      Visionner des vidéos et ressources pédagogiques
      Participe activement dans les discussions si disponibles
    Voit
      Des vidéos longues sans aide immédiate en cas de confusion
      Peu de visibilité sur sa progression
      Des forums ou des canaux de communication limités
