@startuml
package "pkg_Gestion des entretiens individuel" {
    title Use Case - Sprint 2 (Apprenant)

    left to right direction

    actor "Apprenant" as Apprenant

    usecase "Remplir le formulaire de feedback" as UC4
    usecase "Accéder aux ressources pédagogiques" as UC5

    Apprenant -- UC4
    Apprenant -- UC5
}
@enduml