@startuml
package "pkg_Gestion des entretiens individuel" {
    title Use Case - Generale

    left to right direction
    actor Responsable as RF
    
  RF -- (Générer un rapport d’évaluation)
  RF -- (Suivre les progrès)
  RF -- (Gérer des notes )
  
}
@enduml
